#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_DEFAULT_VAL 96
#define RGB_MATRIX_DEFAULT_SPD 25
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
